version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
      - db2
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "warehouse1"
      ACCEPT_EULA: "Y"
  db2:
     image: "mcr.microsoft.com/mssql/server"
     environment:
        SA_PASSWORD: "warehouse2"
        ACCEPT_EULA: "Y"