name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore POC.Calc.API
    - name: Build
      run: dotnet build POC.Calc.API --no-restore
    - name: Test
      run: dotnet test POC.Calc.API --no-build --verbosity normal
